name: Story
description: An individual feature that takes 1-2 weeks to complete
title: "[STORY] "
labels: ["story"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Story Template
        Use this template for individual features that take 1-2 weeks to complete.

  - type: input
    id: story-name
    attributes:
      label: Story Title
      description: A concise title for this story
      placeholder: e.g., "Add sensor data validation to telemetry system"
    validations:
      required: true

  - type: input
    id: related-epic
    attributes:
      label: Related Epic
      description: Which epic does this story belong to?
      placeholder: e.g., "waterloo-rocketry/2025-software-issues#10"
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe this story from a user's perspective
      placeholder: |
        As a [type of user], I want [some goal] so that [some reason].

        Example: As a flight engineer, I want to see real-time sensor data on the ground station so that I can monitor the rocket's status during flight.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific criteria must be met for this story to be considered done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
        - [ ] Testing requirements
        - [ ] Documentation requirements
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Breaking Down into Tasks
      description: What specific tasks need to be completed for this story?
      placeholder: |
        List the individual tasks that make up this story:
        - Task 1: Set up data structures
        - Task 2: Implement validation logic
        - Task 3: Add error handling
        - Task 4: Write unit tests
        - Task 5: Update documentation
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: Estimated Effort
      description: How long do you expect this story to take?
      placeholder: e.g., "1 week", "5-8 days", "2 weeks"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this story?
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What other stories, tasks, or external factors does this depend on?
      placeholder: List any blocking dependencies
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Implementation Notes
      description: Any technical details, approaches, or considerations for implementation
      placeholder: Include relevant technical details, file locations, API changes, etc.
    validations:
      required: false
