name: Task
description: An individual task that takes a few hours of work
title: "[TASK] "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Task Template
        Use this template for individual tasks that take a few hours of work.
        
  - type: input
    id: task-name
    attributes:
      label: Task Title
      description: A concise title for this task
      placeholder: e.g., "Write unit tests for sensor validation function"
    validations:
      required: true
      
  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - "Feature"
        - "Bug"
        - "Documentation"
        - "Testing"
        - "Refactoring"
        - "Research"
        - "Setup/Configuration"
    validations:
      required: true
      
  - type: dropdown
    id: related-story
    attributes:
      label: Related Story
      description: Which story does this task belong to?
      options:
        - "Select a story..."
        - "Sensor Data Validation"
        - "Telemetry Display Interface"
        - "Data Logging System"
        - "Error Handling Framework"
        - "Ground Station Communication"
        - "Flight Computer Initialization"
        - "Other (please specify in description)"
    validations:
      required: true
      
  - type: textarea
    id: task-description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: Describe the work to be completed
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know when this task is complete?
      placeholder: |
        - [ ] Specific deliverable 1
        - [ ] Specific deliverable 2
        - [ ] Testing completed
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - "Low"
        - "Medium"
        - "High" 
        - "Critical"
    validations:
      required: true
      
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any specific implementation details or constraints (optional)
      placeholder: Include relevant technical details, file locations, or approaches
    validations:
      required: false